[package]
name = "diesel_sample"
version = "0.1.0"
authors = ["yagince <straitwalk@gmail.com>"]

[[test]]
name = "tests"
path = "tests/lib.rs"

[dependencies]
diesel = { version = "^1.3.3", features = ["postgres"] }
